#!/usr/bin/perl
use EPrints;

use strict;
my $repository = EPrints->new->current_repository;
exit( 0 ) unless( defined $repository );

my $processor = EPrints::ScreenProcessor->new(session => $repository);

$repository->{processor} = $processor;

my $screen = $repository->plugin("Screen");
$screen->{processor} = $processor;

my $params = {};

if($repository->param("eprintid")){
	my $eprint = $repository->eprint($repository->param("eprintid"));
	$processor->{eprint} = $eprint;
	$processor->{eprintid} = $eprint->get_id;
	$params->{eprintid} = $eprint->get_id;
}

my $list_name = $repository->param("listname");
my $xml = $screen->render_action_list($list_name, $params);

if($repository->param("listtype") eq "bar")
{
	$xml = $screen->render_action_list_bar($list_name, $params);
}

if($repository->param("listtype") eq "icons")
{
	 $xml = $screen->render_action_list_icons($list_name, $params);
}

print $repository->xml->to_string($xml);
